version: '0.3'

services:
  postgres_database:
    env_file:
    - .env
    container_name: pgdb
    hostname: ${PG_HOST}
    image: postgres
    ports:
      - ${PG_POST}:${PG_POST}
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./postgres_${NODE_ENV}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  server:
    env_file:
    - .env
    container_name: server
    ports:
      - ${SERVER_HOST}:${SERVER_HOST}
    build:
      context: ./
      dockerfile: dockerfile
      args:
        - NODE_ENV
    volumes:
        - ./cms-api/usr/src/app
        - /usr/src/app/node_modules
    restart: always
    command: npm run start:dev
    links:
      - postgres_database:${PG_HOST}
    depends_on:
      - postgres_database
    networks:
      - backend

networks:
  backend: